name: Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:    

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      run: |
        wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update; \
          sudo apt-get install -y apt-transport-https && \
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-6.0
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore
#    - name: Publish
#      run: dotnet publish source/gpm.sln -o publish
#    - name: Test
#      run: dotnet test source/gpm.sln --no-build --verbosity normal
   
