name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore
    - name: Test
      run: dotnet test source/gpm.sln --no-build --verbosity normal

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore
    - name: Test
      run: dotnet test source/pm.sln --no-build --verbosity normal
