name: Release

on: 
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:

  build:
    name: release-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore source/gpm.sln
    - name: Build
      run: dotnet build source/gpm.sln --no-restore
      
    - name: Publish
      run: dotnet publish source/gpm/gpm.csproj -o publish
    - uses: papeloto/action-zip@v1
      with:
        files: publish/
        dest: gpm.zip    
    - name: Publish util
      run: dotnet publish source/gpm-util/gpm-util.csproj -o publish-util
    - uses: papeloto/action-zip@v1
      with:
        files: publish-util/
        dest: gpm-util.zip

    - uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
        artifacts: "gpm.zip,gpm-util.zip"
#        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: publish nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: source/gpm/gpm.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: publish nuget util
      id: publish_nuget_util
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: source/gpm-util/gpm-util.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}

